confusion:
  predicted:
  - 0
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 0
  - 1
  - 0
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 0
  - 1
  - 1
  - 1
faucet_left:
  xmax: 573
  xmin: 559
  ymax: 104
  ymin: 80
faucet_right:
  xmax: 593
  xmin: 583
  ymax: 325
  ymin: 305
mqtt:
  host: assure.au-dev.dk
  password: passwordfors1
  port: 1883
  user: s1
topics:
  drinking_behaviour: pig_monitor/section1/pi1/drinking_behaviour
